export default makeWASocket;
declare function makeWASocket(config: import('../Types/Socket.js').SocketConfig): {
    /** from ./interop.js */
    fetchIntegrators: (...args: any[]) => any;
    acceptInteropTOS: (...args: any[]) => any;
    optInIntegrators: (...args: any[]) => any;
    optOutIntegrators: (...args: any[]) => any;
    resolveInteropUser: (...args: any[]) => any;
    resolveInteropUsers: (...args: any[]) => any;
    getReachabilitySettings: (...args: any[]) => any;
    setReachabilitySettings: (...args: any[]) => any;
    blockInteropUser: (...args: any[]) => any;
    unblockInteropUser: (...args: any[]) => any;
    reportInteropSpam: (...args: any[]) => any;
    trustInteropContact: (...args: any[]) => any;
    initInterop: (...args: any[]) => any;
    resetInteropSession: (...args: any[]) => any;
    createInteropGroup: (...args: any[]) => any;
    leaveInteropGroup: (...args: any[]) => any;
    addParticipantsToInteropGroup: (...args: any[]) => any;
    queryInteropGroupInfo: (...args: any[]) => any;
    queryInteropPrivacySettings: (...args: any[]) => any;
    updateInteropPrivacySetting: (...args: any[]) => any;
    updateInteropPrivacySettingWithContactList: (...args: any[]) => any;
    getInteropGroupAddPrivacy: (...args: any[]) => any;
    INTEGRATOR_BIRDYCHAT: Record<string, any>;
    INTEGRATOR_HAIKET: Record<string, any>;
    INTEROP_MEX_QUERY_IDS: Record<string, any>;
    /** from ./privacy.js */
    getPrivacySettings: (...args: any[]) => any;
    setPrivacySetting: (...args: any[]) => any;
    updatePrivacyContactList: (...args: any[]) => any;
    getPrivacyContactList: (...args: any[]) => any;
    updateTextStatus: (...args: any[]) => any;
    getTextStatusList: (...args: any[]) => any;
    updateUserStatus: (...args: any[]) => any;
    fetchUserPictureInfo: (...args: any[]) => any;
    setProfilePictureMex: (...args: any[]) => any;
    accountLogin: (...args: any[]) => any;
    accountLogout: (...args: any[]) => any;
    addMultiAccountLink: (...args: any[]) => any;
    addTrustedDevice: (...args: any[]) => any;
    getTrustedDevices: (...args: any[]) => any;
    untrustTrustedDevice: (...args: any[]) => any;
    deleteTrustedDevice: (...args: any[]) => any;
    revokeMultiAccount: (...args: any[]) => any;
    fetchMobileConfig: (...args: any[]) => any;
    notifyPushName: (...args: any[]) => any;
    contactIntegrityQuery: (...args: any[]) => any;
    bizIntegrityQuery: (...args: any[]) => any;
    linkedProfilesSet: (...args: any[]) => any;
    linkedProfilesRemove: (...args: any[]) => any;
    linkedProfilesUpdate: (...args: any[]) => any;
    migrateBlocklistLid: (...args: any[]) => any;
    qrCodeScan: (...args: any[]) => any;
    PRIVACY_MEX_IDS: Record<string, any>;
    /** from ./registration.js */
    hasPassword: (...args: any[]) => any;
    setPassword: (...args: any[]) => any;
    checkPassword: (...args: any[]) => any;
    deletePassword: (...args: any[]) => any;
    passkeyExists: (...args: any[]) => any;
    passkeyListExists: (...args: any[]) => any;
    passkeyRequestChallenge: (...args: any[]) => any;
    passkeyVerifyChallenge: (...args: any[]) => any;
    passkeyDelete: (...args: any[]) => any;
    regPasskeyStart: (...args: any[]) => any;
    regPasskeyFinish: (...args: any[]) => any;
    regPasskeyEnable: (...args: any[]) => any;
    regPasskeyDisable: (...args: any[]) => any;
    regPasskeyClear: (...args: any[]) => any;
    regPasskeyUpdateEncryptionStatus: (...args: any[]) => any;
    getRegistrationUpsells: (...args: any[]) => any;
    getDynamicRegistrationUpsells: (...args: any[]) => any;
    registrationUpsellShown: (...args: any[]) => any;
    registrationDynamicUpsellShown: (...args: any[]) => any;
    regAccountTransferVerifyToken: (...args: any[]) => any;
    contactsUpload: (...args: any[]) => any;
    contactsBackup: (...args: any[]) => any;
    contactsBackupQuery: (...args: any[]) => any;
    selfContactsQuery: (...args: any[]) => any;
    suggestedContactsV2: (...args: any[]) => any;
    usyncQuery: (...args: any[]) => any;
    userCountryCodeGet: (...args: any[]) => any;
    ageCollection: (...args: any[]) => any;
    getAgeExperience: (...args: any[]) => any;
    setAgeExperience: (...args: any[]) => any;
    getUnkuAgeInfo: (...args: any[]) => any;
    submitAge: (...args: any[]) => any;
    getImagineMeOnboarded: (...args: any[]) => any;
    deleteImagineMeOnboarding: (...args: any[]) => any;
    fetchUserNoticesById: (...args: any[]) => any;
    removeAccountReachoutTimelock: (...args: any[]) => any;
    tosSetResult: (...args: any[]) => any;
    validateVerifierConfidence: (...args: any[]) => any;
    waBinaryDemoQuery: (...args: any[]) => any;
    startChatContextIntegrityQuery: (...args: any[]) => any;
    messageCappingOteRequest: (...args: any[]) => any;
    mobileConfigConsistencyLogging: (...args: any[]) => any;
    reminderCreate: (...args: any[]) => any;
    reminderDelete: (...args: any[]) => any;
    ohaiKeyConfigQuery: (...args: any[]) => any;
    requestPeerLogsUpload: (...args: any[]) => any;
    hasBusinessIntent: (...args: any[]) => any;
    escpsMigration: (...args: any[]) => any;
    createEnforcementAppeal: (...args: any[]) => any;
    getAutoConfChallenge: (...args: any[]) => any;
    getWaOldResponse: (...args: any[]) => any;
    getWaMeLink: (...args: any[]) => any;
    fetchBotPkiCrl: (...args: any[]) => any;
    teeChatParticipationToken: (...args: any[]) => any;
    generateLinkingBundle: (...args: any[]) => any;
    getCacheableUnlinkedBundle: (...args: any[]) => any;
    getUnlinkedBundle: (...args: any[]) => any;
    getDsbInfo: (...args: any[]) => any;
    wamoUserIdVersion: (...args: any[]) => any;
    setWamoUserIdVersion: (...args: any[]) => any;
    wwwCreateAccessToken: (...args: any[]) => any;
    wwwCreateUser: (...args: any[]) => any;
    wwwDeleteUser: (...args: any[]) => any;
    wwwExchangeNonce: (...args: any[]) => any;
    wwwGetCertificates: (...args: any[]) => any;
    wwwGetNonce: (...args: any[]) => any;
    wwwTradeNonces: (...args: any[]) => any;
    wwwTriggerRecovery: (...args: any[]) => any;
    wwwValidateCanonicalUser: (...args: any[]) => any;
    REGISTRATION_MEX_IDS: Record<string, any>;
    /** from ./managed-account.js */
    managedAccountQuery: (...args: any[]) => any;
    managedAccountInitiateLinking: (...args: any[]) => any;
    managedAccountValidateLinking: (...args: any[]) => any;
    managedAccountAcceptLinking: (...args: any[]) => any;
    managedAccountCompleteLinking: (...args: any[]) => any;
    managedAccountRevokeLinking: (...args: any[]) => any;
    managedAccountSyncActivities: (...args: any[]) => any;
    managedAccountUpdatePin: (...args: any[]) => any;
    managedAccountGetSponsorAgeVerification: (...args: any[]) => any;
    paymentsPasskeyHasCredential: (...args: any[]) => any;
    paymentsPasskeyEnrollChallenge: (...args: any[]) => any;
    paymentsPasskeyEnrollVerify: (...args: any[]) => any;
    paymentsPasskeyRegisterFinish: (...args: any[]) => any;
    paymentsPasskeyAuthChallenge: (...args: any[]) => any;
    paymentsPasskeyToggleOn: (...args: any[]) => any;
    paymentsPasskeyToggleOff: (...args: any[]) => any;
    paymentsPasskeyToggleChallenge: (...args: any[]) => any;
    paymentsPasskeyToggleCleanup: (...args: any[]) => any;
    paymentsPasskeyCleanup: (...args: any[]) => any;
    paymentsIsAccountRecoverable: (...args: any[]) => any;
    upiSendOtp: (...args: any[]) => any;
    upiVerifyOtp: (...args: any[]) => any;
    iplsHandshakeInit: (...args: any[]) => any;
    iplsClientHello: (...args: any[]) => any;
    iplsdClientHelloV2: (...args: any[]) => any;
    iplsdClientInitV2: (...args: any[]) => any;
    MANAGED_ACCOUNT_MEX_IDS: Record<string, any>;
    /** from ./graphql.js */
    setAccessToken: (...args: any[]) => any;
    setWamoAuth: (...args: any[]) => any;
    acquireAccessToken: (...args: any[]) => any;
    executeWWWGraphQL: (...args: any[]) => any;
    executeFacebookGraphQL: (...args: any[]) => any;
    executeWamoGraphQL: (...args: any[]) => any;
    aiStudioMemoryQuery: (...args: any[]) => any;
    aiStudioMemoryDelete: (...args: any[]) => any;
    aiStudioMemoryDeleteAll: (...args: any[]) => any;
    metaAiMemoryQuery: (...args: any[]) => any;
    metaAiUnifiedMemoryQuery: (...args: any[]) => any;
    metaAiMemoryDelete: (...args: any[]) => any;
    metaAiMemoryDeleteAll: (...args: any[]) => any;
    metaAiMemoryOptOutStatus: (...args: any[]) => any;
    metaAiMemoryOptOutUpdate: (...args: any[]) => any;
    metaAiCommandGet: (...args: any[]) => any;
    metaAiVoiceOptionsFetch: (...args: any[]) => any;
    metaAiVoiceOptionsWithDefaultFetch: (...args: any[]) => any;
    aiSubscriptionState: (...args: any[]) => any;
    aiSubscriptionUsageData: (...args: any[]) => any;
    imagineEdit: (...args: any[]) => any;
    imagineEditVideo: (...args: any[]) => any;
    imagineExpand: (...args: any[]) => any;
    imagineGenerateAnimate: (...args: any[]) => any;
    imagineIntents: (...args: any[]) => any;
    imagineCanvasContent: (...args: any[]) => any;
    imagineSpotlight: (...args: any[]) => any;
    imagineVideoStatus: (...args: any[]) => any;
    imagineReport: (...args: any[]) => any;
    imagineMeIsOnboarded: (...args: any[]) => any;
    imagineMeOnboarding: (...args: any[]) => any;
    imagineMeOnboardingWithValidation: (...args: any[]) => any;
    imagineMeDeleteOnboarding: (...args: any[]) => any;
    imagineEditVideoStyles: (...args: any[]) => any;
    aiCreationFetchCreatedBot: (...args: any[]) => any;
    aiCreationUpdatePersona: (...args: any[]) => any;
    aiCreationDeletePersona: (...args: any[]) => any;
    aiCreationUploadImage: (...args: any[]) => any;
    aiCreationCheckCreatedByMe: (...args: any[]) => any;
    aiCreationFetchVoiceSample: (...args: any[]) => any;
    aiHomeFetchUserCreatedPersonas: (...args: any[]) => any;
    aiHomeSearch: (...args: any[]) => any;
    aiCharacterUpdateHideStatus: (...args: any[]) => any;
    botProactiveMessageControlStatus: (...args: any[]) => any;
    botProactiveMessageControlUpdate: (...args: any[]) => any;
    botProfilesSync: (...args: any[]) => any;
    avatarUserRecovery: (...args: any[]) => any;
    loadAvatarPoses: (...args: any[]) => any;
    saveAvatarPose: (...args: any[]) => any;
    selectedOrDefaultPose: (...args: any[]) => any;
    createEvent: (...args: any[]) => any;
    getEvent: (...args: any[]) => any;
    updateEvent: (...args: any[]) => any;
    deleteEvent: (...args: any[]) => any;
    listEvents: (...args: any[]) => any;
    updateEventRsvp: (...args: any[]) => any;
    addEventInvitations: (...args: any[]) => any;
    removeEventInvitations: (...args: any[]) => any;
    removeSelfEventInvitation: (...args: any[]) => any;
    getOrCreateEventInviteLink: (...args: any[]) => any;
    rotateEventInviteLink: (...args: any[]) => any;
    getEventLinkPreview: (...args: any[]) => any;
    listPresetCoverImages: (...args: any[]) => any;
    getBusinessProfileWebsiteShimUrl: (...args: any[]) => any;
    waWebBizCreateOrderJob: (...args: any[]) => any;
    waWebBizGraphqlRefreshCart: (...args: any[]) => any;
    waWebBizQueryOrderJob: (...args: any[]) => any;
    whatsappCatalogReportProduct: (...args: any[]) => any;
    brandIdsGetPhoneNumbers: (...args: any[]) => any;
    businessInteractionPills: (...args: any[]) => any;
    externalCtxAuthoriseWAChat: (...args: any[]) => any;
    brGetAuthOptions: (...args: any[]) => any;
    brSaveCpf: (...args: any[]) => any;
    brCreateEnrollment: (...args: any[]) => any;
    brCompleteEnrollmentRegistration: (...args: any[]) => any;
    brGetEnrollmentOptions: (...args: any[]) => any;
    brAuthorizePayment: (...args: any[]) => any;
    getPixBankList: (...args: any[]) => any;
    getMerchantPixInfo: (...args: any[]) => any;
    completePixTransaction: (...args: any[]) => any;
    payWithPixPrecheck: (...args: any[]) => any;
    paymentHealthChecks: (...args: any[]) => any;
    getPaymentKey: (...args: any[]) => any;
    genCreatePaymentKey: (...args: any[]) => any;
    genUpdatePaymentKey: (...args: any[]) => any;
    genDeletePaymentKey: (...args: any[]) => any;
    getBillerPlans: (...args: any[]) => any;
    getBillReceipt: (...args: any[]) => any;
    getBillComplaintUrl: (...args: any[]) => any;
    paymentReminderCreate: (...args: any[]) => any;
    paymentReminderGet: (...args: any[]) => any;
    paymentReminderCancel: (...args: any[]) => any;
    paymentReminderStop: (...args: any[]) => any;
    genShareRemittanceIntent: (...args: any[]) => any;
    getRemittanceTransactionDetails: (...args: any[]) => any;
    saveRemittancePaymentMessageId: (...args: any[]) => any;
    saveSenderPaymentMessagePreference: (...args: any[]) => any;
    getEligibility: (...args: any[]) => any;
    enrollAndGetIncentiveReferralId: (...args: any[]) => any;
    getSubscriptionsAndFeatureFlags: (...args: any[]) => any;
    getUpiAccounts: (...args: any[]) => any;
    getUpiLiteDetails: (...args: any[]) => any;
    getUpiToken: (...args: any[]) => any;
    getUpiPurposeLimitingKey: (...args: any[]) => any;
    upiCreateMandate: (...args: any[]) => any;
    upiAcceptMandate: (...args: any[]) => any;
    upiRejectMandate: (...args: any[]) => any;
    upiExecuteMandate: (...args: any[]) => any;
    upiPauseMandate: (...args: any[]) => any;
    upiResumeMandate: (...args: any[]) => any;
    upiRevokeMandate: (...args: any[]) => any;
    pmtaGetAiControls: (...args: any[]) => any;
    pmtaSetAiControls: (...args: any[]) => any;
    wamoSubQueryStatus: (...args: any[]) => any;
    wamoSubCancelSubscription: (...args: any[]) => any;
    wamoSubOverrideStatus: (...args: any[]) => any;
    wamoAfsSubscriptionInfo: (...args: any[]) => any;
    wamoPromoIdQuery: (...args: any[]) => any;
    wamoPromoIdSet: (...args: any[]) => any;
    wamoPromoIdDelete: (...args: any[]) => any;
    facebookAccountName: (...args: any[]) => any;
    instagramAccountName: (...args: any[]) => any;
    getSignupMetadata: (...args: any[]) => any;
    registerInit: (...args: any[]) => any;
    registerAllAccounts: (...args: any[]) => any;
    checkDeviceRegistration: (...args: any[]) => any;
    canonicalEntQueryFeature: (...args: any[]) => any;
    canonicalEntSetupFeature: (...args: any[]) => any;
    canonicalEntTeardownFeature: (...args: any[]) => any;
    wwwCanonicalUserValid: (...args: any[]) => any;
    waffleUserAgeCheck: (...args: any[]) => any;
    getAiPredictedAge: (...args: any[]) => any;
    submitBugReport: (...args: any[]) => any;
    supportContactForm: (...args: any[]) => any;
    createGroupSuspensionAppeal: (...args: any[]) => any;
    createDogfoodingTask: (...args: any[]) => any;
    hatchChannelLink: (...args: any[]) => any;
    hatchChannelMetadata: (...args: any[]) => any;
    oxygenChannelOptIn: (...args: any[]) => any;
    oxygenChannelOptOut: (...args: any[]) => any;
    oxygenChannelStatus: (...args: any[]) => any;
    paslGetLoggerConfig: (...args: any[]) => any;
    quickPromotionBatchFetch: (...args: any[]) => any;
    waQuickPromotionLog: (...args: any[]) => any;
    waSupportMessageFeedback: (...args: any[]) => any;
    waGizmoPostMetadata: (...args: any[]) => any;
    unifiedConversationStarters: (...args: any[]) => any;
    getSubscribedTasksForThread: (...args: any[]) => any;
    editGenAiTask: (...args: any[]) => any;
    deleteGenAiTasks: (...args: any[]) => any;
    deleteUserBillAccount: (...args: any[]) => any;
    metaPoiTypeAhead: (...args: any[]) => any;
    metaConfigFetch: (...args: any[]) => any;
    bizAlertsNotificationList: (...args: any[]) => any;
    bizAlertsUpdate: (...args: any[]) => any;
    ctwaAdsContextBiz: (...args: any[]) => any;
    digitalContentIapPurchaseQuote: (...args: any[]) => any;
    getCompliance: (...args: any[]) => any;
    setCompliance: (...args: any[]) => any;
    getCustomUrls: (...args: any[]) => any;
    getDcpProducts: (...args: any[]) => any;
    acDcCreateCommerceNonce: (...args: any[]) => any;
    fbUsernameRecommendations: (...args: any[]) => any;
    wamoUserBasic: (...args: any[]) => any;
    wamoCreateUser: (...args: any[]) => any;
    wamoDeleteUser: (...args: any[]) => any;
    wamoLinkUser: (...args: any[]) => any;
    wamoHeartbeat: (...args: any[]) => any;
    wamoHidePage: (...args: any[]) => any;
    wamoUnhidePage: (...args: any[]) => any;
    wamoUnhidePageV2: (...args: any[]) => any;
    wamoHidePromo: (...args: any[]) => any;
    wamoReportPromo: (...args: any[]) => any;
    wamoStartViewerSession: (...args: any[]) => any;
    wamoBloksGetLayout: (...args: any[]) => any;
    wamoDyiJobCreate: (...args: any[]) => any;
    wamoDyiJobDelete: (...args: any[]) => any;
    wamoDyiJobStatus: (...args: any[]) => any;
    metaAiFeedback: (...args: any[]) => any;
    metaAiStopGeneration: (...args: any[]) => any;
    metaAiModesQuery: (...args: any[]) => any;
    fetchMetaAiModes: (...args: any[]) => any;
    metaAiRichPlaceDetails: (...args: any[]) => any;
    metaAiSideBySideSurveyResponse: (...args: any[]) => any;
    metaAiBizAgentVoiceAttachments: (...args: any[]) => any;
    metaAiCustomizationGenAiSetMode: (...args: any[]) => any;
    metaAiIntentCardNuxEligibilityReset: (...args: any[]) => any;
    metaAiIntentCardNuxImpression: (...args: any[]) => any;
    metaAiIntentCardNuxImpressionQuery: (...args: any[]) => any;
    maiUnifiedUser: (...args: any[]) => any;
    maiUnifiedUserQuery: (...args: any[]) => any;
    maiUnifiedUserReset: (...args: any[]) => any;
    memuProfileQuery: (...args: any[]) => any;
    memuUpdateProfile: (...args: any[]) => any;
    memuPreviewPhoto: (...args: any[]) => any;
    updateMemuSelfie: (...args: any[]) => any;
    addMemuProfilePhotos: (...args: any[]) => any;
    createMemuProfile: (...args: any[]) => any;
    fbMemuPermissionQuery: (...args: any[]) => any;
    getMemuStickerById: (...args: any[]) => any;
    genAiVerifyMemuPhotos: (...args: any[]) => any;
    genAiMeMenuUpdateVoice: (...args: any[]) => any;
    genAiSocialEntityDetails: (...args: any[]) => any;
    genAiImagineGenerate: (...args: any[]) => any;
    genAiImagineGenerateFlash: (...args: any[]) => any;
    genAiImagineGenerateStreaming: (...args: any[]) => any;
    genAiImagineGenerateFromImage: (...args: any[]) => any;
    genAiImagineRegenerate: (...args: any[]) => any;
    genAiImagineEdit: (...args: any[]) => any;
    genAiImagineCanvasApi: (...args: any[]) => any;
    genAiImagineInspirationCanvasApi: (...args: any[]) => any;
    genAiImagineSuggestions: (...args: any[]) => any;
    genAiImagineDownloadMedia: (...args: any[]) => any;
    genAiImagineSendMediaToChat: (...args: any[]) => any;
    genAiImagineBulkSendMediaToChat: (...args: any[]) => any;
    genAiImagineHasMemuProfile: (...args: any[]) => any;
    genAiImagineUpdateMemuProfilePermission: (...args: any[]) => any;
    genAiImaginePromptSummarization: (...args: any[]) => any;
    genAiImagineRestyleSections: (...args: any[]) => any;
    genAiImagineBulkFor3pIntents: (...args: any[]) => any;
    dropInImagineGenerate: (...args: any[]) => any;
    genAiEditAnimate: (...args: any[]) => any;
    genAiEditBackdropSuggestions: (...args: any[]) => any;
    genAiEditImageBackdrop: (...args: any[]) => any;
    genAiEditSuggestions: (...args: any[]) => any;
    genAiEditUploadAuthenticImage: (...args: any[]) => any;
    immersiveCreationComplete: (...args: any[]) => any;
    immersiveCreationConfig: (...args: any[]) => any;
    simpleEcho: (...args: any[]) => any;
    WWW_GQL_IDS: Record<string, any>;
    FACEBOOK_GQL_IDS: Record<string, any>;
    WAMO_GQL_IDS: Record<string, any>;
    CLIENT_PERSIST_GQL_IDS: Record<string, any>;
    ENDPOINTS: Record<string, any>;
    communityQuery: (jid: any, type: any, content: any) => Promise<any>;
    communityMetadata: (jid: any) => Promise<{
        id: any;
        subject: any;
        subjectOwner: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        desc: any;
        descId: any;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
        addressingMode: any;
    }>;
    communityCreate: (subject: any, body: any) => Promise<{
        id: any;
        notify: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
        subjectOwnerPn: any;
        subjectOwnerUsername: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        ownerPn: string | undefined;
        ownerUsername: any;
        owner_country_code: any;
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerPn: string | undefined;
        descOwnerUsername: any;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
    } | null>;
    communityCreateGroup: (subject: any, participants: any, parentCommunityJid: any) => Promise<{
        id: any;
        notify: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
        subjectOwnerPn: any;
        subjectOwnerUsername: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        ownerPn: string | undefined;
        ownerUsername: any;
        owner_country_code: any;
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerPn: string | undefined;
        descOwnerUsername: any;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
    } | null>;
    communityLeave: (id: any) => Promise<void>;
    communityUpdateSubject: (jid: any, subject: any) => Promise<void>;
    communityLinkGroup: (groupJid: any, parentCommunityJid: any) => Promise<void>;
    communityUnlinkGroup: (groupJid: any, parentCommunityJid: any) => Promise<void>;
    communityFetchLinkedGroups: (jid: any) => Promise<{
        communityJid: any;
        isCommunity: boolean;
        linkedGroups: {
            id: string | undefined;
            subject: any;
            creation: number | undefined;
            owner: string | undefined;
            size: number | undefined;
        }[];
    }>;
    communityRequestParticipantsList: (jid: any) => Promise<any>;
    communityRequestParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    communityParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    communityUpdateDescription: (jid: any, description: any) => Promise<void>;
    communityInviteCode: (jid: any) => Promise<any>;
    communityRevokeInvite: (jid: any) => Promise<any>;
    communityAcceptInvite: (code: any) => Promise<any>;
    communityRevokeInviteV4: (communityJid: any, invitedJid: any) => Promise<boolean>;
    communityAcceptInviteV4: (...args: any[]) => Promise<any>;
    communityGetInviteInfo: (code: any) => Promise<{
        id: any;
        subject: any;
        subjectOwner: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        desc: any;
        descId: any;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
        addressingMode: any;
    }>;
    communityToggleEphemeral: (jid: any, ephemeralExpiration: any) => Promise<void>;
    communitySettingUpdate: (jid: any, setting: any) => Promise<void>;
    communityMemberAddMode: (jid: any, mode: any) => Promise<void>;
    communityJoinApprovalMode: (jid: any, mode: any) => Promise<void>;
    communityFetchAllParticipating: () => Promise<{}>;
    logger: any;
    getOrderDetails: (orderId: any, tokenBase64: any) => Promise<{
        price: {
            total: number;
            currency: any;
        };
        products: any;
    }>;
    getCatalog: ({ jid, limit, cursor }: {
        jid: any;
        limit: any;
        cursor: any;
    }) => Promise<{
        products: any;
        nextPageCursor: any;
    }>;
    getCollections: (jid: any, limit?: number) => Promise<{
        collections: any;
    }>;
    productCreate: (create: any) => Promise<{
        id: any;
        imageUrls: {
            requested: any;
            original: any;
        };
        reviewStatus: {
            whatsapp: any;
        };
        availability: string;
        name: any;
        retailerId: any;
        url: any;
        description: any;
        price: number;
        currency: any;
        isHidden: boolean;
    }>;
    productDelete: (productIds: any) => Promise<{
        deleted: number;
    }>;
    productUpdate: (productId: any, update: any) => Promise<{
        id: any;
        imageUrls: {
            requested: any;
            original: any;
        };
        reviewStatus: {
            whatsapp: any;
        };
        availability: string;
        name: any;
        retailerId: any;
        url: any;
        description: any;
        price: number;
        currency: any;
        isHidden: boolean;
    }>;
    updateBussinesProfile: (args: any) => Promise<any>;
    updateBusinessProfile: (args: any) => Promise<any>;
    updateCoverPhoto: (photo: any) => Promise<any>;
    removeCoverPhoto: (id: any) => Promise<any>;
    sendMessageAck: (node: any, errorCode: any) => Promise<void>;
    sendRetryRequest: (node: any, forceIncludeKeys?: boolean) => Promise<void>;
    rejectCall: (callId: any, callFrom: any) => Promise<void>;
    fetchMessageHistory: (count: any, oldestMsgKey: any, oldestMsgTimestamp: any) => Promise<any>;
    requestPlaceholderResend: (messageKey: any, msgData: any) => Promise<any>;
    messageRetryManager: import("../index.js").MessageRetryManager | null;
    userDevicesCache: any;
    devicesMutex: {
        mutex(code: any): any;
    };
    issuePrivacyTokens: (jids: any, timestamp: any) => Promise<any>;
    assertSessions: (jids: any, force: any) => Promise<boolean>;
    relayMessage: (jid: any, message: any, { messageId: msgId, participant, additionalAttributes, additionalNodes, useUserDevicesCache, useCachedGroupMetadata, addBizAttributes, statusJidList, statusPrivacy }: {
        messageId: any;
        participant: any;
        additionalAttributes: any;
        additionalNodes: any;
        useUserDevicesCache: any;
        useCachedGroupMetadata: any;
        addBizAttributes: any;
        statusJidList: any;
        statusPrivacy: any;
    }) => Promise<any>;
    sendReceipt: (jid: any, participant: any, messageIds: any, type: any) => Promise<void>;
    sendReceipts: (keys: any, type: any) => Promise<void>;
    readMessages: (keys: any) => Promise<void>;
    refreshMediaConn: (forceGet?: boolean) => Promise<any>;
    getMediaHost: () => string;
    waUploadToServer: (filePath: any, { mediaType, fileEncSha256B64, timeoutMs, newsletter }: {
        mediaType: any;
        fileEncSha256B64: any;
        timeoutMs: any;
        newsletter: any;
    }) => Promise<{
        mediaUrl: any;
        directPath: any;
        meta_hmac: any;
        fbid: any;
        ts: any;
        thumbnailDirectPath: any;
        thumbnailSha256: any;
    }>;
    fetchPrivacySettings: (force?: boolean) => Promise<any>;
    sendPeerDataOperationMessage: (pdoMessage: any) => Promise<any>;
    createParticipantNodes: (recipientJids: any, message: any, extraAttrs: any, dsmMessage: any) => Promise<{
        nodes: any[];
        shouldIncludeDeviceIdentity: boolean;
    }>;
    getUSyncDevices: (jids: any, useCache: any, ignoreZeroDevices: any) => Promise<any[]>;
    updateMemberLabel: (jid: any, memberLabel: any) => Promise<any>;
    updateMediaMessage: (message: any) => Promise<any>;
    sendMessage: (jid: any, content: any, options?: {}) => Promise<import("../index.js").proto.WebMessageInfo | undefined>;
    executeWMexQuery: (variables: any, queryId: any, dataPath: any) => Promise<any>;
    newsletterCreate: (name: any, description: any) => Promise<{
        id: any;
        owner: undefined;
        name: any;
        creation_time: number;
        description: any;
        invite: any;
        subscribers: number;
        verification: any;
        picture: {
            id: any;
            directPath: any;
        };
        mute_state: any;
    }>;
    newsletterUpdate: (jid: any, updates: any) => Promise<any>;
    newsletterSubscribers: (jid: any) => Promise<any>;
    newsletterSubscribed: () => Promise<any>;
    newsletterMetadata: (type: any, key: any) => Promise<any>;
    newsletterFollow: (jid: any) => Promise<any>;
    newsletterUnfollow: (jid: any) => Promise<any>;
    newsletterMute: (jid: any) => Promise<any>;
    newsletterUnmute: (jid: any) => Promise<any>;
    newsletterUpdateName: (jid: any, name: any) => Promise<any>;
    newsletterUpdateDescription: (jid: any, description: any) => Promise<any>;
    newsletterUpdatePicture: (jid: any, content: any) => Promise<any>;
    newsletterRemovePicture: (jid: any) => Promise<any>;
    newsletterReactMessage: (jid: any, serverId: any, reaction: any) => Promise<void>;
    newsletterFetchMessages: (type: any, key: any, count: any, after: any, before: any) => Promise<{
        [k: string]: any;
    }[]>;
    subscribeNewsletterUpdates: (jid: any) => Promise<{
        duration: any;
    } | null>;
    newsletterAdminCount: (jid: any) => Promise<any>;
    newsletterChangeOwner: (jid: any, newOwnerJid: any) => Promise<void>;
    newsletterDemote: (jid: any, userJid: any) => Promise<void>;
    newsletterDelete: (jid: any) => Promise<void>;
    groupQuery: (jid: any, type: any, content: any) => Promise<any>;
    groupMetadata: (jid: any) => Promise<{
        id: any;
        notify: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
        subjectOwnerPn: any;
        subjectOwnerUsername: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        ownerPn: string | undefined;
        ownerUsername: any;
        owner_country_code: any;
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerPn: string | undefined;
        descOwnerUsername: any;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
    }>;
    groupCreate: (subject: any, participants: any) => Promise<{
        id: any;
        notify: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
        subjectOwnerPn: any;
        subjectOwnerUsername: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        ownerPn: string | undefined;
        ownerUsername: any;
        owner_country_code: any;
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerPn: string | undefined;
        descOwnerUsername: any;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
    }>;
    groupLeave: (id: any) => Promise<void>;
    groupUpdateSubject: (jid: any, subject: any) => Promise<void>;
    groupRequestParticipantsList: (jid: any) => Promise<any>;
    groupRequestParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    groupParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    groupUpdateDescription: (jid: any, description: any) => Promise<void>;
    groupInviteCode: (jid: any) => Promise<any>;
    groupRevokeInvite: (jid: any) => Promise<any>;
    groupAcceptInvite: (code: any) => Promise<any>;
    groupRevokeInviteV4: (groupJid: any, invitedJid: any) => Promise<boolean>;
    groupAcceptInviteV4: (...args: any[]) => Promise<any>;
    groupGetInviteInfo: (code: any) => Promise<{
        id: any;
        notify: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
        subjectOwnerPn: any;
        subjectOwnerUsername: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: string | undefined;
        ownerPn: string | undefined;
        ownerUsername: any;
        owner_country_code: any;
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerPn: string | undefined;
        descOwnerUsername: any;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
    }>;
    groupToggleEphemeral: (jid: any, ephemeralExpiration: any) => Promise<void>;
    groupSettingUpdate: (jid: any, setting: any) => Promise<void>;
    groupMemberAddMode: (jid: any, mode: any) => Promise<void>;
    groupJoinApprovalMode: (jid: any, mode: any) => Promise<void>;
    groupFetchAllParticipating: () => Promise<{}>;
    findUserId: (pnLid: any) => Promise<{
        lid: undefined;
        phoneNumber: undefined;
    }>;
    serverProps: {
        privacyTokenOn1to1: boolean;
        profilePicPrivacyToken: boolean;
        lidTrustedTokenIssueToLid: boolean;
    };
    createCallLink: (type: any, event: any, timeoutMs: any) => Promise<any>;
    getBotListV2: () => Promise<{
        jid: any;
        personaId: any;
    }[]>;
    messageMutex: {
        mutex(code: any): any;
    };
    receiptMutex: {
        mutex(code: any): any;
    };
    appStatePatchMutex: {
        mutex(code: any): any;
    };
    notificationMutex: {
        mutex(code: any): any;
    };
    upsertMessage: (...args: any[]) => Promise<any>;
    appPatch: (patchCreate: any) => Promise<void>;
    sendPresenceUpdate: (type: any, toJid: any) => Promise<void>;
    presenceSubscribe: (toJid: any) => Promise<void>;
    profilePictureUrl: (jid: any, type?: string, timeoutMs?: number, shouldIncludeTcToken?: boolean) => Promise<any>;
    fetchBlocklist: () => Promise<any>;
    fetchStatus: (...jids: any[]) => Promise<any>;
    fetchDisappearingDuration: (...jids: any[]) => Promise<any>;
    updateProfilePicture: (jid: any, content: any, dimensions: any) => Promise<void>;
    removeProfilePicture: (jid: any) => Promise<void>;
    updateProfileStatus: (status: any) => Promise<void>;
    updateProfileName: (name: any) => Promise<void>;
    updateBlockStatus: (jid: any, action: any) => Promise<void>;
    updateDisableLinkPreviewsPrivacy: (isPreviewsDisabled: any) => Promise<void>;
    updateCallPrivacy: (value: any) => Promise<void>;
    updateMessagesPrivacy: (value: any) => Promise<void>;
    updateLastSeenPrivacy: (value: any) => Promise<void>;
    updateOnlinePrivacy: (value: any) => Promise<void>;
    updateProfilePicturePrivacy: (value: any) => Promise<void>;
    updateStatusPrivacy: (value: any) => Promise<void>;
    updateReadReceiptsPrivacy: (value: any) => Promise<void>;
    updateGroupsAddPrivacy: (value: any) => Promise<void>;
    updateDefaultDisappearingMode: (duration: any) => Promise<void>;
    getBusinessProfile: (jid: any) => Promise<{
        wid: any;
        address: any;
        description: any;
        website: any[];
        email: any;
        category: any;
        business_hours: {
            timezone: any;
            business_config: any;
        };
    } | undefined>;
    resyncAppState: (...args: any[]) => Promise<any>;
    chatModify: (mod: any, jid: any) => Promise<void>;
    cleanDirtyBits: (type: any, fromTimestamp: any) => Promise<void>;
    addOrEditContact: (jid: any, contact: any) => Promise<void>;
    removeContact: (jid: any) => Promise<void>;
    placeholderResendCache: any;
    addLabel: (jid: any, labels: any) => Promise<void>;
    addChatLabel: (jid: any, labelId: any) => Promise<void>;
    removeChatLabel: (jid: any, labelId: any) => Promise<void>;
    addMessageLabel: (jid: any, messageId: any, labelId: any) => Promise<void>;
    removeMessageLabel: (jid: any, messageId: any, labelId: any) => Promise<void>;
    star: (jid: any, messages: any, star: any) => Promise<void>;
    addOrEditQuickReply: (quickReply: any) => Promise<void>;
    removeQuickReply: (timestamp: any) => Promise<void>;
    type: string;
    ws: import("./Client/websocket.js").WebSocketClient;
    ev: import('../Types/Events.js').BaileysEventEmitter;
    authState: {
        creds: any;
        keys: {
            get: (type: any, ids: any) => Promise<any>;
            set: (data: any) => Promise<void>;
            isInTransaction: () => boolean;
            transaction: (work: any, key: any) => Promise<any>;
        };
    };
    signalRepository: any;
    user: any;
    generateMessageTag: () => string;
    query: (node: any, timeoutMs: any) => Promise<any>;
    waitForMessage: (msgId: any, timeoutMs?: any) => Promise<any>;
    waitForSocketOpen: () => Promise<void>;
    sendRawMessage: (data: any) => Promise<void>;
    sendNode: (frame: any) => Promise<void>;
    logout: (msg: any) => Promise<void>;
    end: (error: any) => Promise<void>;
    registerSocketEndHandler: (handler: any) => void;
    onUnexpectedError: (err: any, msg: any) => void;
    uploadPreKeys: (count?: number) => Promise<void>;
    uploadPreKeysToServerIfRequired: () => Promise<void>;
    digestKeyBundle: () => Promise<void>;
    rotateSignedPreKey: () => Promise<void>;
    requestPairingCode: (phoneNumber: string, customPairingCode?: string) => Promise<string>;
    updateServerTimeOffset: ({ attrs }: {
        attrs: any;
    }) => void;
    sendUnifiedSession: () => Promise<void>;
    wamBuffer: import("../index.js").BinaryInfo;
    waitForConnectionUpdate: (check: any, timeoutMs: any) => Promise<void>;
    sendWAMBuffer: (wamBuffer: any) => Promise<any>;
    executeUSyncQuery: (usyncQuery: any) => Promise<any>;
    onWhatsApp: (...phoneNumber: any[]) => Promise<any>;
    onWhatsAppUsername: (...queries: (string | {
        username: string;
        usernameKey?: string;
        lid?: string;
    })[]) => Promise<{
        username: string;
        jid: any;
        exists: boolean;
        keyRequired: boolean;
        isBusiness: boolean;
        pnJid: string | undefined;
    }[]>;
    fetchUsername: (...jids: any[]) => Promise<{
        jid: any;
        username: string | undefined;
    }[]>;
    checkUsername: (username: string, includeSuggestions?: boolean, sessionId?: string) => Promise<{
        available: boolean;
        username: string;
        session_id: string;
        suggestions?: string[];
        rejectionReasons?: string[];
        suggestionsEligible?: boolean;
    }>;
    setUsername: (username: string, options?: {
        source?: string;
        sessionId?: string;
        pin?: string;
    }) => Promise<any>;
    deleteUsername: () => Promise<any>;
    getMyUsername: () => Promise<any>;
    setUsernamePin: (pin: string | null) => Promise<any>;
    fetchAccountReachoutTimelock: () => Promise<{
        isActive: boolean;
        timeEnforcementEnds: Date | undefined;
        enforcementType: any;
    }>;
    fetchNewChatMessageCap: () => Promise<any>;
};
//# sourceMappingURL=index.d.ts.map
